[package]
name = "rust"
version = "0.1.0"
authors = ["Chung-Chiang Cheng <cccheng@synology.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
